migliorato programma ma errore
fixato errore precedente ma ne sopraggiunge un altro: quando si vuole accedere al risultato della classificazione per ILP -> raise PrologError("".join(["Caused by: '", query, "'. ",
pyswip.prolog.PrologError: Caused by: 'classifica([radius = small, mass_class = terran, density = high, gravity = medium,  eqtemp = acceptable, composition = ga Classe).'. Returned: 'error(existence_error(procedure, /(<==, 2)), context(/(classifica, 2), _4606))'.